metrics_enabled : false
debug : true
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - org.skife
    - xx-responses
    - com.hello

ntp_clock_tolerance: 60000
ntp_client_timeout: 2000

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 1111
      idleTimeout: 25 seconds
  adminConnectors:
    - type: http
      port: 1112
      idleTimeout: 25 seconds
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/hello-time/hello-time-access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /var/log/hello-time/hello-time-access-%d{yyyy-MM-dd}.log.gz
        archivedFileCount: 7
      - type: papertrail
        host: logs2.papertrailapp.com
        port: 11366
        ident: hello-time-dev

logging:
  level: INFO
  loggers:
    com.hello.suripu: INFO
  appenders:
    - type: file
      threshold: INFO
      currentLogFilename: /var/log/hello-time/hello-time.log
      archivedLogFilenamePattern: /var/log/hello-time/hello-time-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: hello-time-dev
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

dynamodb:
  region: us-east-1
  tables:
    features : features
    sense_key_store : key_store
    teams : teams

  endpoints:
      features : http://dynamodb.us-east-1.amazonaws.com
      sense_key_store : http://dynamodb.us-east-1.amazonaws.com
      teams : http://dynamodb.us-east-1.amazonaws.com