metrics_enabled : false
debug : true
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - org.skife
    - xx-responses
    - com.hello

common_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 8

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 1111
      idleTimeout: 25 seconds
  adminConnectors:
    - type: http
      port: 2222
      idleTimeout: 25 seconds
  requestLog:
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: /var/log/hello-time/hello-time-access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /var/log/hello-time/hello-time-access-%d{yyyy-MM-dd}.log.gz
        archivedFileCount: 7
      - type: papertrail
        host: logs2.papertrailapp.com
        port: 11366
        ident: hello-time-dev

logging:
  level: INFO
  loggers:
    com.hello.suripu: INFO
  appenders:
    - type: file
      threshold: INFO
      currentLogFilename: /var/log/hello-time/hello-time.log
      archivedLogFilenamePattern: /var/log/hello-time/hello-time-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: hello-time-dev
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    activity_stream : activity_stream
    logs: dev-logs
  
kinesis_logger:
  stream_name: logs
  enabled : false
  buffer_size: 100
  origin: hello-time

dynamodb:
  region: us-east-1
  tables:
    features : features
    sense_key_store : key_store
    teams : teams

  endpoints:
      features : http://dynamodb.us-east-1.amazonaws.com
      sense_key_store : http://dynamodb.us-east-1.amazonaws.com
      teams : http://dynamodb.us-east-1.amazonaws.com